
    drop table bw_adminGroupMembers if exists;

    drop table bw_adminGroups if exists;

    drop table bw_alarm_attendees if exists;

    drop table bw_alarm_xprops if exists;

    drop table bw_alarmdescriptions if exists;

    drop table bw_alarms if exists;

    drop table bw_alarmsummaries if exists;

    drop table bw_attachments if exists;

    drop table bw_attendees if exists;

    drop table bw_auth if exists;

    drop table bw_authprefCalendars if exists;

    drop table bw_authprefCategories if exists;

    drop table bw_authprefContacts if exists;

    drop table bw_authprefLocations if exists;

    drop table bw_calendar_categories if exists;

    drop table bw_calendar_properties if exists;

    drop table bw_calendars if exists;

    drop table bw_calsuites if exists;

    drop table bw_categories if exists;

    drop table bw_collection_lastmods if exists;

    drop table bw_contacts if exists;

    drop table bw_entity_alarms if exists;

    drop table bw_entity_attachments if exists;

    drop table bw_event_annotations if exists;

    drop table bw_event_attendees if exists;

    drop table bw_event_availuids if exists;

    drop table bw_event_categories if exists;

    drop table bw_event_comments if exists;

    drop table bw_event_contacts if exists;

    drop table bw_event_descriptions if exists;

    drop table bw_event_exdates if exists;

    drop table bw_event_exrules if exists;

    drop table bw_event_rdates if exists;

    drop table bw_event_recipients if exists;

    drop table bw_event_resources if exists;

    drop table bw_event_rrules if exists;

    drop table bw_event_summaries if exists;

    drop table bw_event_xprops if exists;

    drop table bw_eventann_alarms if exists;

    drop table bw_eventann_attachments if exists;

    drop table bw_eventann_attendees if exists;

    drop table bw_eventann_categories if exists;

    drop table bw_eventann_comments if exists;

    drop table bw_eventann_contacts if exists;

    drop table bw_eventann_descriptions if exists;

    drop table bw_eventann_exdates if exists;

    drop table bw_eventann_exrules if exists;

    drop table bw_eventann_rdates if exists;

    drop table bw_eventann_recipients if exists;

    drop table bw_eventann_resources if exists;

    drop table bw_eventann_rrules if exists;

    drop table bw_eventann_rstatus if exists;

    drop table bw_eventann_summaries if exists;

    drop table bw_eventann_xprops if exists;

    drop table bw_events if exists;

    drop table bw_fbcomp if exists;

    drop table bw_filter_descriptions if exists;

    drop table bw_filter_display_names if exists;

    drop table bw_filters if exists;

    drop table bw_group_Members if exists;

    drop table bw_groups if exists;

    drop table bw_locations if exists;

    drop table bw_longstrings if exists;

    drop table bw_preferences if exists;

    drop table bw_recurrences if exists;

    drop table bw_resource_contents if exists;

    drop table bw_resources if exists;

    drop table bw_rstatus if exists;

    drop table bw_sched_msg if exists;

    drop table bw_settings if exists;

    drop table bw_strings if exists;

    drop table bw_system_properties if exists;

    drop table bw_user_properties if exists;

    drop table bw_user_views if exists;

    drop table bw_users if exists;

    drop table bw_view_collections if exists;

    drop table bw_views if exists;

    create table bw_adminGroupMembers (
        bw_groupid integer not null,
        memberid integer not null,
        member_is_group char(255) not null,
        primary key (bw_groupid, memberid, member_is_group)
    );

    create table bw_adminGroups (
        bw_groupid integer generated by default as identity,
        bwseq integer not null,
        account varchar(255) not null,
        bw_principal_ref varchar(255) not null,
        description varchar(2000),
        bw_group_owner varchar(255) not null,
        bw_owner varchar(255) not null,
        primary key (bw_groupid)
    );

    create table bw_alarm_attendees (
        alarmid integer not null,
        attendeeid integer not null,
        primary key (alarmid, attendeeid)
    );

    create table bw_alarm_xprops (
        alarmid integer not null,
        bwxp_position integer not null,
        bw_name varchar(100),
        bw_pars varchar(4000),
        bw_value varchar(2147483647),
        primary key (alarmid, bwxp_position)
    );

    create table bw_alarmdescriptions (
        bw_alarmid integer not null,
        bw_strid integer not null,
        primary key (bw_alarmid, bw_strid)
    );

    create table bw_alarms (
        alarmid integer generated by default as identity,
        bwseq integer not null,
        alarm_type integer,
        bw_owner varchar(255) not null,
        publick char(255) not null,
        trigger_rfctime varchar(16),
        trigger_start char(255) not null,
        duration varchar(100),
        repetitions integer,
        attach varchar(2000),
        expired char(255) not null,
        primary key (alarmid)
    );

    create table bw_alarmsummaries (
        bw_alarmid integer not null,
        bw_strid integer not null,
        primary key (bw_alarmid, bw_strid)
    );

    create table bw_attachments (
        bwid integer generated by default as identity,
        bw_fmttype varchar(20),
        bw_valuetype varchar(20),
        bw_encoding varchar(2000),
        bw_uri varchar(2000),
        bw_value varchar(2147483647),
        primary key (bwid)
    );

    create table bw_attendees (
        attendeeid integer generated by default as identity,
        cn varchar(2000),
        cutype varchar(2000),
        delegated_from varchar(2000),
        delegated_to varchar(2000),
        dir varchar(2000),
        lang varchar(100),
        member varchar(2000),
        rsvp char(255),
        role varchar(200),
        partstat varchar(100),
        sent_by varchar(2000),
        attendee_uri varchar(2000),
        rfcsequence integer,
        bw_sched_agent integer,
        bw_sched_status varchar(100),
        dtstamp varchar(16),
        primary key (attendeeid)
    );

    create table bw_auth (
        userid integer generated by default as identity,
        bwseq integer not null,
        bw_user varchar(255) not null,
        autoaddCategories char(255) not null,
        autoaddLocations char(255) not null,
        autoaddContacts char(255) not null,
        autoaddCalendars char(255) not null,
        usertype integer,
        primary key (userid)
    );

    create table bw_authprefCalendars (
        userid integer not null,
        calendarid integer not null,
        primary key (userid, calendarid)
    );

    create table bw_authprefCategories (
        userid integer not null,
        categoryid integer not null,
        primary key (userid, categoryid)
    );

    create table bw_authprefContacts (
        userid integer not null,
        contactid integer not null,
        primary key (userid, contactid)
    );

    create table bw_authprefLocations (
        userid integer not null,
        locationid integer not null,
        primary key (userid, locationid)
    );

    create table bw_calendar_categories (
        calendarid integer not null,
        categoryid integer not null,
        primary key (calendarid, categoryid)
    );

    create table bw_calendar_properties (
        bwid integer not null,
        bw_name varchar(200),
        bw_value varchar(2147483647)
    );

    create table bw_calendars (
        id integer generated by default as identity,
        bwseq integer not null,
        bw_creator varchar(255),
        bw_owner varchar(255),
        bwaccess varchar(3900),
        publick char(255) not null,
        calname varchar(100) not null,
        bwpath varchar(3000) not null,
        bw_col_path varchar(3000),
        summary varchar(500),
        description varchar(1000),
        mail_list_id varchar(200),
        caltype integer not null,
        bw_created varchar(16) not null,
        bw_filterexpr varchar(2147483647),
        bw_alias_uri varchar(500),
        display char(255) not null,
        affects_free_busy char(255) not null,
        ignore_transparency char(255) not null,
        unremoveable char(255) not null,
        bwrefreshseconds integer,
        bwlastrefresh varchar(16),
        bwlastetag varchar(256),
        bwrid varchar(256),
        bwrpw varchar(500),
        primary key (id)
    );

    create table bw_calsuites (
        csid integer generated by default as identity,
        bwseq integer not null,
        bw_creator varchar(255),
        bw_owner varchar(255),
        bwaccess varchar(3900),
        publick char(255) not null,
        csname varchar(255) not null,
        groupid integer not null,
        bw_root_collection varchar(3000),
        bw_submissions_root varchar(3000),
        primary key (csid)
    );

    create table bw_categories (
        categoryid integer generated by default as identity,
        bwseq integer not null,
        bw_creator varchar(255),
        bw_owner varchar(255),
        bwaccess varchar(3900),
        publick char(255) not null,
        bw_catwdid integer not null,
        bw_catdescid integer,
        bw_uid varchar(50) not null,
        primary key (categoryid)
    );

    create table bw_collection_lastmods (
        bw_id integer not null,
        bwpath varchar(3000) not null,
        bw_timestamp varchar(16) not null,
        bw_sequence integer,
        primary key (bw_id)
    );

    create table bw_contacts (
        entityid integer generated by default as identity,
        bwseq integer not null,
        bw_creator varchar(255),
        bw_owner varchar(255),
        bwaccess varchar(3900),
        publick char(255) not null,
        bw_uid varchar(50) not null,
        bw_connameid integer not null,
        bw_phone varchar(255),
        bw_email varchar(255),
        bw_link varchar(500),
        primary key (entityid)
    );

    create table bw_entity_alarms (
        eventid integer not null,
        alarmid integer not null,
        primary key (eventid, alarmid)
    );

    create table bw_entity_attachments (
        eventid integer not null,
        attachid integer not null,
        primary key (eventid, attachid)
    );

    create table bw_event_annotations (
        eventid integer generated by default as identity,
        bwseq integer not null,
        bw_entity_type integer,
        bw_col_path varchar(3000) not null,
        eventname varchar(500),
        bw_uid varchar(1000),
        bw_creator varchar(255),
        bw_owner varchar(255),
        bwaccess varchar(3900),
        publick char(255),
        start_date_type char(255),
        start_tzid varchar(255),
        start_dtval varchar(16),
        start_date varchar(16),
        bw_start_floating char(255),
        end_date_type char(255),
        end_tzid varchar(255),
        end_dtval varchar(16),
        end_date varchar(16),
        bw_end_floating char(255),
        duration varchar(255),
        end_type char(255),
        bw_nostart char(255),
        bw_deleted char(255),
        bwtombstoned char(255) not null,
        bw_class varchar(250),
        bw_link varchar(500),
        bw_geolatitude decimal(19,2),
        bw_geolongitude decimal(19,2),
        status varchar(255),
        cost varchar(255),
        bw_dtstamp varchar(16),
        bw_lastmod varchar(16),
        bw_created varchar(16),
        bw_stag varchar(21),
        priority integer,
        locationid integer,
        rfcsequence integer,
        transparency varchar(100),
        percent_complete integer,
        completed varchar(16),
        recurring char(255),
        recurrence_id varchar(16),
        latest_date varchar(255),
        schedule_method integer,
        originator varchar(255),
        bw_org_cn varchar(500),
        bw_org_dir varchar(500),
        bw_org_lang varchar(100),
        bw_org_sentby varchar(500),
        bw_org_uri varchar(500),
        bw_org_sched_status varchar(100),
        bw_org_dtstamp varchar(16),
        bw_reltype varchar(100),
        bw_reltoval varchar(500),
        schedule_state integer,
        targetid integer,
        masterid integer,
        bw_override char(255) not null,
        bw_empty_flags varchar(200),
        primary key (eventid)
    );

    create table bw_event_attendees (
        eventid integer not null,
        attendeeid integer not null,
        primary key (eventid, attendeeid)
    );

    create table bw_event_availuids (
        eventid integer not null,
        avluid varchar(255) not null,
        primary key (eventid, avluid)
    );

    create table bw_event_categories (
        eventid integer not null,
        categoryid integer not null,
        primary key (eventid, categoryid)
    );

    create table bw_event_comments (
        bw_eventid integer not null,
        bw_strid integer not null,
        primary key (bw_eventid, bw_strid)
    );

    create table bw_event_contacts (
        eventid integer not null,
        contactid integer not null,
        primary key (eventid, contactid)
    );

    create table bw_event_descriptions (
        bw_eventid integer not null,
        bw_strid integer not null,
        primary key (bw_eventid, bw_strid)
    );

    create table bw_event_exdates (
        eventid integer not null,
        ex_date_type char(255) not null,
        ex_tzid varchar(255),
        ex_dtval varchar(16) not null,
        ex_date varchar(16) not null,
        primary key (eventid, ex_date_type, ex_dtval, ex_date)
    );

    create table bw_event_exrules (
        eventid integer not null,
        exrule varchar(255) not null,
        primary key (eventid, exrule)
    );

    create table bw_event_rdates (
        eventid integer not null,
        r_date_type char(255) not null,
        r_tzid varchar(255),
        r_dtval varchar(16) not null,
        r_date varchar(16) not null,
        primary key (eventid, r_date_type, r_dtval, r_date)
    );

    create table bw_event_recipients (
        eventid integer not null,
        recipient varchar(255) not null,
        primary key (eventid, recipient)
    );

    create table bw_event_resources (
        bw_eventid integer not null,
        bw_strid integer not null,
        primary key (bw_eventid, bw_strid)
    );

    create table bw_event_rrules (
        eventid integer not null,
        rrule varchar(255) not null,
        primary key (eventid, rrule)
    );

    create table bw_event_summaries (
        bw_eventid integer not null,
        bw_strid integer not null,
        primary key (bw_eventid, bw_strid)
    );

    create table bw_event_xprops (
        bw_eventid integer not null,
        bwxp_position integer not null,
        bw_name varchar(100),
        bw_pars varchar(4000),
        bw_value varchar(2147483647),
        primary key (bw_eventid, bwxp_position)
    );

    create table bw_eventann_alarms (
        eventid integer not null,
        alarmid integer not null,
        primary key (eventid, alarmid)
    );

    create table bw_eventann_attachments (
        eventid integer not null,
        attachid integer not null,
        primary key (eventid, attachid)
    );

    create table bw_eventann_attendees (
        eventid integer not null,
        attendeeid integer not null,
        primary key (eventid, attendeeid)
    );

    create table bw_eventann_categories (
        eventid integer not null,
        categoryid integer not null,
        primary key (eventid, categoryid)
    );

    create table bw_eventann_comments (
        bw_eventid integer not null,
        bw_strid integer not null,
        primary key (bw_eventid, bw_strid)
    );

    create table bw_eventann_contacts (
        eventid integer not null,
        contactid integer not null,
        primary key (eventid, contactid)
    );

    create table bw_eventann_descriptions (
        bw_eventid integer not null,
        bw_strid integer not null,
        primary key (bw_eventid, bw_strid)
    );

    create table bw_eventann_exdates (
        eventid integer not null,
        ex_date_type char(255) not null,
        ex_tzid varchar(255),
        ex_dtval varchar(16) not null,
        ex_date varchar(16) not null,
        primary key (eventid, ex_date_type, ex_dtval, ex_date)
    );

    create table bw_eventann_exrules (
        eventid integer not null,
        exrule varchar(255) not null,
        primary key (eventid, exrule)
    );

    create table bw_eventann_rdates (
        eventid integer not null,
        r_date_type char(255) not null,
        r_tzid varchar(255),
        r_dtval varchar(16) not null,
        r_date varchar(16) not null,
        primary key (eventid, r_date_type, r_dtval, r_date)
    );

    create table bw_eventann_recipients (
        eventid integer not null,
        recipient varchar(255) not null,
        primary key (eventid, recipient)
    );

    create table bw_eventann_resources (
        bw_eventid integer not null,
        bw_strid integer not null,
        primary key (bw_eventid, bw_strid)
    );

    create table bw_eventann_rrules (
        eventid integer not null,
        rrule varchar(255)
    );

    create table bw_eventann_rstatus (
        eventid integer not null,
        bw_rscode varchar(100),
        bw_rsdescid integer,
        bw_rsdata varchar(250)
    );

    create table bw_eventann_summaries (
        bw_eventid integer not null,
        bw_strid integer not null,
        primary key (bw_eventid, bw_strid)
    );

    create table bw_eventann_xprops (
        bw_eventannid integer not null,
        bwxp_position integer not null,
        bw_name varchar(100),
        bw_pars varchar(4000),
        bw_value varchar(2147483647),
        primary key (bw_eventannid, bwxp_position)
    );

    create table bw_events (
        eventid integer generated by default as identity,
        bwseq integer not null,
        bw_entity_type integer,
        bw_col_path varchar(3000) not null,
        bw_uid varchar(1000),
        eventname varchar(500),
        bw_creator varchar(255),
        bw_owner varchar(255),
        bwaccess varchar(3900),
        publick char(255) not null,
        start_date_type char(255),
        start_tzid varchar(255),
        start_dtval varchar(16),
        start_date varchar(16),
        bw_start_floating char(255),
        end_date_type char(255),
        end_tzid varchar(255),
        end_dtval varchar(16),
        end_date varchar(16),
        bw_end_floating char(255),
        duration varchar(255),
        end_type char(255) not null,
        bw_nostart char(255) not null,
        bw_deleted char(255) not null,
        bwtombstoned char(255) not null,
        bw_class varchar(250),
        bw_link varchar(500),
        bw_geolatitude decimal(19,2),
        bw_geolongitude decimal(19,2),
        status varchar(255),
        cost varchar(255),
        bw_dtstamp varchar(16),
        bw_lastmod varchar(16) not null,
        bw_created varchar(16) not null,
        bw_stag varchar(21),
        priority integer,
        locationid integer,
        rfcsequence integer,
        transparency varchar(100),
        percent_complete integer,
        completed varchar(16),
        recurring char(255) not null,
        recurrence_id varchar(16),
        latest_date varchar(255),
        schedule_method integer,
        originator varchar(255),
        bw_org_cn varchar(500),
        bw_org_dir varchar(500),
        bw_org_lang varchar(100),
        bw_org_sentby varchar(500),
        bw_org_uri varchar(500),
        bw_org_sched_status varchar(100),
        bw_org_dtstamp varchar(16),
        bw_reltype varchar(100),
        bw_reltoval varchar(500),
        schedule_state integer,
        bw_org_scheduleobj boolean not null,
        bw_att_scheduleobj boolean not null,
        busy_type integer,
        primary key (eventid)
    );

    create table bw_fbcomp (
        bwid integer generated by default as identity,
        bwseq integer not null,
        bwtype integer,
        bwvalue varchar(3900),
        eventid integer,
        fbcomp_position integer,
        primary key (bwid)
    );

    create table bw_filter_descriptions (
        bw_eventid integer not null,
        bw_strid integer not null,
        primary key (bw_eventid, bw_strid)
    );

    create table bw_filter_display_names (
        bw_eventid integer not null,
        bw_strid integer not null,
        primary key (bw_eventid, bw_strid)
    );

    create table bw_filters (
        filterid integer generated by default as identity,
        bwseq integer not null,
        bw_owner varchar(255),
        publick char(255) not null,
        filtername varchar(200),
        bwdefinition varchar(2147483647),
        primary key (filterid)
    );

    create table bw_group_Members (
        groupid integer not null,
        memberid integer not null,
        member_is_group char(255) not null,
        primary key (groupid, memberid, member_is_group)
    );

    create table bw_groups (
        bw_group_id integer generated by default as identity,
        bwseq integer not null,
        bw_account varchar(200) not null,
        bw_principal_ref varchar(255) not null,
        primary key (bw_group_id)
    );

    create table bw_locations (
        entityid integer generated by default as identity,
        bwseq integer not null,
        bw_creator varchar(255),
        bw_owner varchar(255),
        bwaccess varchar(3900),
        publick char(255) not null,
        bw_uid varchar(50) not null,
        bw_locaddrid integer not null,
        bw_locsubaddrid integer,
        bw_link varchar(500),
        primary key (entityid)
    );

    create table bw_longstrings (
        bw_id integer generated by default as identity,
        bwseq integer not null,
        bw_lang varchar(100),
        bw_value varchar(2147483647),
        primary key (bw_id)
    );

    create table bw_preferences (
        prefid integer generated by default as identity,
        bwseq integer not null,
        bw_owner varchar(255) not null,
        email varchar(255),
        bw_default_calendar varchar(3900),
        skin_name varchar(255),
        skin_style varchar(255),
        preferred_view varchar(255),
        preferred_view_period varchar(255),
        bw_page_size integer,
        workdays varchar(255),
        workday_start integer,
        workday_end integer,
        preferred_endtype varchar(255),
        bwuser_mode integer,
        bw_hour24 char(255) not null,
        bw_sched_autoresp char(255) not null,
        bw_sched_autocancelaction integer,
        bw_sched_double_book char(255) not null,
        bw_sched_autoproc_resp integer,
        primary key (prefid)
    );

    create table bw_recurrences (
        recurrence_id varchar(16) not null,
        masterid integer not null,
        bwseq integer not null,
        start_date_type char(255) not null,
        start_tzid varchar(255),
        start_dtval varchar(16) not null,
        start_date varchar(16) not null,
        bw_rstart_floating char(255),
        end_date_type char(255),
        end_tzid varchar(255),
        end_dtval varchar(255),
        end_date varchar(255),
        bw_rend_floating char(255),
        overrideid integer,
        primary key (recurrence_id, masterid)
    );

    create table bw_resource_contents (
        id integer generated by default as identity,
        bwseq integer not null,
        bw_col_path varchar(3000),
        bwname varchar(100) not null,
        bw_value blob,
        primary key (id)
    );

    create table bw_resources (
        id integer generated by default as identity,
        bwseq integer not null,
        bw_col_path varchar(3000) not null,
        bw_creator varchar(255),
        bw_owner varchar(255),
        bwaccess varchar(3900),
        publick char(255) not null,
        bwname varchar(100) not null,
        bw_created varchar(16) not null,
        bw_lastmod varchar(16) not null,
        bwsequence integer,
        bw_contenttype varchar(1000),
        bw_encoding varchar(1000),
        bwcontent_length bigint,
        primary key (id)
    );

    create table bw_rstatus (
        eventid integer not null,
        bw_rscode varchar(100),
        bw_rsdescid integer,
        bw_rsdata varchar(250)
    );

    create table bw_sched_msg (
        id integer generated by default as identity,
        bwseq integer not null,
        bw_timestamp varchar(16) not null,
        bw_sequence integer,
        bw_lastproc varchar(16) not null,
        bw_inbox char(255) not null,
        bw_principal_href varchar(255),
        bw_eventname varchar(500),
        bw_recurrence_id varchar(16),
        primary key (id)
    );

    create table bw_settings (
        id integer generated by default as identity,
        bwseq integer not null,
        bwname varchar(200),
        primary key (id)
    );

    create table bw_strings (
        bw_id integer generated by default as identity,
        bwseq integer not null,
        bw_lang varchar(100),
        bw_value varchar(3900),
        primary key (bw_id)
    );

    create table bw_system_properties (
        bwid integer not null,
        bw_name varchar(200),
        bw_value varchar(2147483647)
    );

    create table bw_user_properties (
        bwid integer not null,
        bw_name varchar(200),
        bw_value varchar(2147483647)
    );

    create table bw_user_views (
        prefid integer not null,
        elt integer not null,
        primary key (prefid, elt)
    );

    create table bw_users (
        userid integer generated by default as identity,
        bwseq integer not null,
        bw_account varchar(200) not null,
        bw_principal_ref varchar(255) not null,
        instance_owner char(255) not null,
        bw_created timestamp,
        bw_last_logon timestamp,
        bw_last_access timestamp,
        bw_last_modify timestamp,
        bw_category_access varchar(3900),
        bw_contact_access varchar(3900),
        bw_location_access varchar(3900),
        bw_quota bigint,
        primary key (userid)
    );

    create table bw_view_collections (
        viewid integer not null,
        bw_path_positon integer not null,
        bw_calpath varchar(255) not null,
        primary key (viewid, bw_path_positon)
    );

    create table bw_views (
        viewid integer generated by default as identity,
        bwseq integer not null,
        viewname varchar(100) not null,
        primary key (viewid)
    );
create index bwidx_ag_href on bw_adminGroups (bw_principal_ref);
create index bwidx_ag_group_owner on bw_adminGroups (bw_group_owner);
create index bwidx_ag_owner on bw_adminGroups (bw_owner);

    alter table bw_adminGroups 
        add constraint ag-key unique (account);

    alter table bw_alarmdescriptions 
        add constraint UK_m2efnj4j34psfevyqfbyria0r unique (bw_strid);
create index bwidx_alarm_owner on bw_alarms (bw_owner);

    alter table bw_alarmsummaries 
        add constraint UK_agd2njwc0ubud5jjkc69guvyv unique (bw_strid);
create index bwidx_au_user on bw_auth (bw_user);
create index bwidx_cal_creator on bw_calendars (bw_creator);
create index bwidx_cal_owner on bw_calendars (bw_owner);
create index bwidx_calpath on bw_calendars (bwpath);
create index bwidx_cal_colpath on bw_calendars (bw_col_path);
create index bwidx_cals_creator on bw_calsuites (bw_creator);
create index bwidx_cals_owner on bw_calsuites (bw_owner);
create index bwidx_calsuite_group on bw_calsuites (groupid);
create index bwidx_cs_rootcol on bw_calsuites (bw_root_collection);
create index bwidx_cs_subroot on bw_calsuites (bw_submissions_root);

    alter table bw_calsuites 
        add constraint UK_f09xf5tetup3aurknv6wmkdl9 unique (csname);
create index bwidx_cat_creator on bw_categories (bw_creator);
create index bwidx_cat_owner on bw_categories (bw_owner);
create index bwidx_category_uid on bw_categories (bw_uid);

    alter table bw_categories 
        add constraint UK_paxb6fb83dq83lmy7xqskalir unique (bw_catwdid);

    alter table bw_categories 
        add constraint UK_ftcs94ltjhsems3eo52bwsyjc unique (bw_catdescid);

    alter table bw_categories 
        add constraint UK_hdp94b0mo4p6n8tbq4haa0b6e unique (bw_uid);
create index bwidx_collm_path on bw_collection_lastmods (bwpath);
create index bwidx_con_creator on bw_contacts (bw_creator);
create index bwidx_con_owner on bw_contacts (bw_owner);
create index bwidx_contact_uid on bw_contacts (bw_uid);

    alter table bw_contacts 
        add constraint UK_ni5bidef7j8dasot6j9rls9ft unique (bw_uid);

    alter table bw_contacts 
        add constraint UK_ipa5dcrtyhqmnedhujrnv61iy unique (bw_connameid);
create index bwidx_eann_colpath on bw_event_annotations (bw_col_path);
create index bwidx_eann_creator on bw_event_annotations (bw_creator);
create index bwidx_eann_owner on bw_event_annotations (bw_owner);
create index bwidx_eann_start on bw_event_annotations (start_date);
create index bwidx_eann_start_floating on bw_event_annotations (bw_start_floating);
create index bwidx_eann_end on bw_event_annotations (end_date);
create index bwidx_eann_end_floating on bw_event_annotations (bw_end_floating);
create index bwidx_eann_deleted on bw_event_annotations (bw_deleted);
create index bwidx_eann_tombstoned on bw_event_annotations (bwtombstoned);
create index bwidx_eann_location on bw_event_annotations (locationid);
create index bwidx_eann_recurring on bw_event_annotations (recurring);
create index bwidx_eann_latest_date on bw_event_annotations (latest_date);

    alter table bw_event_comments 
        add constraint UK_bepvx4dr6ye3g0mlsojd4nghn unique (bw_strid);

    alter table bw_event_descriptions 
        add constraint UK_p12g7wi7540mfrt30uemikb9g unique (bw_strid);
create index bwidx_event_exdate on bw_event_exdates (ex_date);
create index bwidx_event_rdate on bw_event_rdates (r_date);

    alter table bw_event_resources 
        add constraint UK_hi8pvu1cr6qxcgsftqj8hynw6 unique (bw_strid);

    alter table bw_event_summaries 
        add constraint UK_q6rhxb656g69a28at99idwsfl unique (bw_strid);

    alter table bw_eventann_comments 
        add constraint UK_8j4d2yhjitnl760neelf5j89 unique (bw_strid);

    alter table bw_eventann_descriptions 
        add constraint UK_lqxnyoqmw2b1l0bcvij4p088j unique (bw_strid);
create index bwidx_eann_exdate on bw_eventann_exdates (ex_date);
create index bwidx_eann_rdate on bw_eventann_rdates (r_date);

    alter table bw_eventann_resources 
        add constraint UK_pjflu0vdw36yud2kfnw3phxe9 unique (bw_strid);

    alter table bw_eventann_rstatus 
        add constraint UK_bf1kxjooqbu67ommghucv9j1w unique (bw_rsdescid);

    alter table bw_eventann_summaries 
        add constraint UK_lvsyvk6tp09glefmhkqmwgsvi unique (bw_strid);
create index bwidx_ev_colpath on bw_events (bw_col_path);
create index bwidx_event_cal_name_uid on bw_events (bw_uid, eventname);
create index bwidx_event_creator on bw_events (bw_creator);
create index bwidx_event_owner on bw_events (bw_owner);
create index bwidx_event_start on bw_events (start_date);
create index bwidx_event_start_floating on bw_events (bw_start_floating);
create index bwidx_event_end on bw_events (end_date);
create index bwidx_event_end_floating on bw_events (bw_end_floating);
create index bwidx_event_deleted on bw_events (bw_deleted);
create index bwidx_event_tombstoned on bw_events (bwtombstoned);
create index bwidx_event_location on bw_events (locationid);
create index bwidx_event_recurring on bw_events (recurring);
create index bwidx_event_latest_date on bw_events (latest_date);
create index bw_idx_orgsobj on bw_events (bw_org_scheduleobj);
create index bw_idx_attsobj on bw_events (bw_att_scheduleobj);

    alter table bw_filter_descriptions 
        add constraint UK_8mkcck8e5s63dt8fbh33sru7g unique (bw_strid);

    alter table bw_filter_display_names 
        add constraint UK_kuosxtu558hmi9rwoq6dynt7d unique (bw_strid);
create index bwidx_flt_owner on bw_filters (bw_owner);
create index bwidx_grp_href on bw_groups (bw_principal_ref);

    alter table bw_groups 
        add constraint group-key unique (bw_account);
create index bwidx_loc_creator on bw_locations (bw_creator);
create index bwidx_loc_owner on bw_locations (bw_owner);
create index bwidx_loc_uid on bw_locations (bw_uid);

    alter table bw_locations 
        add constraint UK_cl1g4ns6am8r9xpcrdun4kxaw unique (bw_uid);

    alter table bw_locations 
        add constraint UK_irp22ttf09p8dhtf4k5d3rxup unique (bw_locaddrid);

    alter table bw_locations 
        add constraint UK_eq0qj3ayoi4tiossejlgbojrw unique (bw_locsubaddrid);
create index bwidx_prefs_owner on bw_preferences (bw_owner);

    alter table bw_preferences 
        add constraint UK_64ge5mxj9s57m7lwhyjsrro4i unique (bw_owner);
create index bwidx_recur_start on bw_recurrences (start_date);
create index bwidx_rstart_floating on bw_recurrences (bw_rstart_floating);
create index bwidx_recur_end on bw_recurrences (end_date);
create index bwidx_rend_floating on bw_recurrences (bw_rend_floating);
create index bwidx_rsrc_content_colpath on bw_resource_contents (bw_col_path);
create index bwidx_rsrc_colpath on bw_resources (bw_col_path);
create index bwidx_rsrc_creator on bw_resources (bw_creator);
create index bwidx_rsrc_owner on bw_resources (bw_owner);

    alter table bw_rstatus 
        add constraint UK_9xeub1vinqx3cs9jpwgx70xsu unique (bw_rsdescid);
create index bwidx_smsg_timestamp on bw_sched_msg (bw_timestamp);
create index bwidx_smsg_principal on bw_sched_msg (bw_principal_href);
create index bwidx_smsg_eventname on bw_sched_msg (bw_eventname);
create index bwidx_user_href on bw_users (bw_principal_ref);
create index bwidx_user_instance_owner on bw_users (instance_owner);

    alter table bw_users 
        add constraint user-key unique (bw_account);

    alter table bw_adminGroupMembers 
        add constraint bw_agm_ag_fk 
        foreign key (bw_groupid) 
        references bw_adminGroups;

    alter table bw_alarm_attendees 
        add constraint bw_aa_att_fk 
        foreign key (attendeeid) 
        references bw_attendees;

    alter table bw_alarm_attendees 
        add constraint bw_aa_alarm_fk 
        foreign key (alarmid) 
        references bw_alarms;

    alter table bw_alarm_xprops 
        add constraint bw_alarmxp_aid_fk 
        foreign key (alarmid) 
        references bw_alarms;

    alter table bw_alarmdescriptions 
        add constraint bw_ad_str_fk 
        foreign key (bw_strid) 
        references bw_strings;

    alter table bw_alarmdescriptions 
        add constraint bw_ad_alarm_fk 
        foreign key (bw_alarmid) 
        references bw_alarms;

    alter table bw_alarmsummaries 
        add constraint bw_as_str_fk 
        foreign key (bw_strid) 
        references bw_strings;

    alter table bw_alarmsummaries 
        add constraint bw_as_alarm_fk 
        foreign key (bw_alarmid) 
        references bw_alarms;

    alter table bw_authprefCalendars 
        add constraint bw_apcal_cal_fk1 
        foreign key (calendarid) 
        references bw_calendars;

    alter table bw_authprefCalendars 
        add constraint bw_apcal_ap_fk1 
        foreign key (userid) 
        references bw_auth;

    alter table bw_authprefCategories 
        add constraint bw_apcat_cat_fk1 
        foreign key (categoryid) 
        references bw_categories;

    alter table bw_authprefCategories 
        add constraint bw_apcat_ap_fk1 
        foreign key (userid) 
        references bw_auth;

    alter table bw_authprefContacts 
        add constraint bw_apcon_con_fk1 
        foreign key (contactid) 
        references bw_contacts;

    alter table bw_authprefContacts 
        add constraint bw_apcon_ap_fk1 
        foreign key (userid) 
        references bw_auth;

    alter table bw_authprefLocations 
        add constraint bw_aploc_loc_fk1 
        foreign key (locationid) 
        references bw_locations;

    alter table bw_authprefLocations 
        add constraint bw_aploc_ap_fk1 
        foreign key (userid) 
        references bw_auth;

    alter table bw_calendar_categories 
        add constraint bw_cal_cat_fk 
        foreign key (categoryid) 
        references bw_categories;

    alter table bw_calendar_categories 
        add constraint bw_calcat_cid_fk 
        foreign key (calendarid) 
        references bw_calendars;

    alter table bw_calendar_properties 
        add constraint bw_calprp_pid_fk 
        foreign key (bwid) 
        references bw_calendars;

    alter table bw_calsuites 
        add constraint bw_cs_ag_fk 
        foreign key (groupid) 
        references bw_adminGroups;

    alter table bw_categories 
        add constraint bw_cat_wd_fk 
        foreign key (bw_catwdid) 
        references bw_strings;

    alter table bw_categories 
        add constraint bw_cat_desc_fk 
        foreign key (bw_catdescid) 
        references bw_strings;

    alter table bw_collection_lastmods 
        add constraint FKgqubrhm95m6nvsqtoul0oyobf 
        foreign key (bw_id) 
        references bw_calendars;

    alter table bw_contacts 
        add constraint bw_con_name_fk 
        foreign key (bw_connameid) 
        references bw_strings;

    alter table bw_entity_alarms 
        add constraint bw_event_alarm_fk 
        foreign key (alarmid) 
        references bw_alarms;

    alter table bw_entity_alarms 
        add constraint bw_eventalm_eid_fk 
        foreign key (eventid) 
        references bw_events;

    alter table bw_entity_attachments 
        add constraint bw_event_attach_fk 
        foreign key (attachid) 
        references bw_attachments;

    alter table bw_entity_attachments 
        add constraint bw_eventattach_eid_fk 
        foreign key (eventid) 
        references bw_events;

    alter table bw_event_annotations 
        add constraint bw_eann_loc_fk 
        foreign key (locationid) 
        references bw_locations;

    alter table bw_event_annotations 
        add constraint bw_eann_tgt_fk 
        foreign key (targetid) 
        references bw_events;

    alter table bw_event_annotations 
        add constraint bw_eann_mstr_fk 
        foreign key (masterid) 
        references bw_events;

    alter table bw_event_attendees 
        add constraint bw_event_att_fk 
        foreign key (attendeeid) 
        references bw_attendees;

    alter table bw_event_attendees 
        add constraint bw_eventatt_eid_fk 
        foreign key (eventid) 
        references bw_events;

    alter table bw_event_availuids 
        add constraint bw_event_avluid_fk 
        foreign key (eventid) 
        references bw_events;

    alter table bw_event_categories 
        add constraint bw_event_cat_fk 
        foreign key (categoryid) 
        references bw_categories;

    alter table bw_event_categories 
        add constraint bw_eventcat_eid_fk 
        foreign key (eventid) 
        references bw_events;

    alter table bw_event_comments 
        add constraint bw_event_com_fk 
        foreign key (bw_strid) 
        references bw_strings;

    alter table bw_event_comments 
        add constraint bw_eventcom_eid_fk 
        foreign key (bw_eventid) 
        references bw_events;

    alter table bw_event_contacts 
        add constraint bw_event_con_fk 
        foreign key (contactid) 
        references bw_contacts;

    alter table bw_event_contacts 
        add constraint bw_eventcon_eid_fk 
        foreign key (eventid) 
        references bw_events;

    alter table bw_event_descriptions 
        add constraint bw_event_desc_fk 
        foreign key (bw_strid) 
        references bw_longstrings;

    alter table bw_event_descriptions 
        add constraint bw_eventdesc_eid_fk 
        foreign key (bw_eventid) 
        references bw_events;

    alter table bw_event_exdates 
        add constraint bw_event_edate_fk 
        foreign key (eventid) 
        references bw_events;

    alter table bw_event_exrules 
        add constraint bw_event_erule_fk 
        foreign key (eventid) 
        references bw_events;

    alter table bw_event_rdates 
        add constraint bw_event_rdate_fk 
        foreign key (eventid) 
        references bw_events;

    alter table bw_event_recipients 
        add constraint bw_event_recip_fk 
        foreign key (eventid) 
        references bw_events;

    alter table bw_event_resources 
        add constraint bw_event_res_fk 
        foreign key (bw_strid) 
        references bw_strings;

    alter table bw_event_resources 
        add constraint bw_eventres_eid_fk 
        foreign key (bw_eventid) 
        references bw_events;

    alter table bw_event_rrules 
        add constraint bw_event_rrule_fk 
        foreign key (eventid) 
        references bw_events;

    alter table bw_event_summaries 
        add constraint bw_event_sum_fk 
        foreign key (bw_strid) 
        references bw_strings;

    alter table bw_event_summaries 
        add constraint bw_eventsum_eid_fk 
        foreign key (bw_eventid) 
        references bw_events;

    alter table bw_event_xprops 
        add constraint bw_eventxp_eid_fk 
        foreign key (bw_eventid) 
        references bw_events;

    alter table bw_eventann_alarms 
        add constraint bw_eann_alarm_fk 
        foreign key (alarmid) 
        references bw_alarms;

    alter table bw_eventann_alarms 
        add constraint bw_eannalm_eid_fk 
        foreign key (eventid) 
        references bw_event_annotations;

    alter table bw_eventann_attachments 
        add constraint bw_eann_attach_fk 
        foreign key (attachid) 
        references bw_attachments;

    alter table bw_eventann_attachments 
        add constraint bw_eannattach_eid_fk 
        foreign key (eventid) 
        references bw_event_annotations;

    alter table bw_eventann_attendees 
        add constraint bw_eann_att_fk 
        foreign key (attendeeid) 
        references bw_attendees;

    alter table bw_eventann_attendees 
        add constraint bw_eannatt_eid_fk 
        foreign key (eventid) 
        references bw_event_annotations;

    alter table bw_eventann_categories 
        add constraint bw_eann_cat_fk 
        foreign key (categoryid) 
        references bw_categories;

    alter table bw_eventann_categories 
        add constraint bw_eanncat_eid_fk 
        foreign key (eventid) 
        references bw_event_annotations;

    alter table bw_eventann_comments 
        add constraint bw_eann_com_fk 
        foreign key (bw_strid) 
        references bw_strings;

    alter table bw_eventann_comments 
        add constraint bw_eanncom_eid_fk 
        foreign key (bw_eventid) 
        references bw_event_annotations;

    alter table bw_eventann_contacts 
        add constraint bw_eann_con_fk 
        foreign key (contactid) 
        references bw_contacts;

    alter table bw_eventann_contacts 
        add constraint bw_eanncon_eid_fk 
        foreign key (eventid) 
        references bw_event_annotations;

    alter table bw_eventann_descriptions 
        add constraint bw_eann_desc_fk 
        foreign key (bw_strid) 
        references bw_longstrings;

    alter table bw_eventann_descriptions 
        add constraint bw_eanndesc_eid_fk 
        foreign key (bw_eventid) 
        references bw_event_annotations;

    alter table bw_eventann_exdates 
        add constraint bw_eann_edate_fk 
        foreign key (eventid) 
        references bw_event_annotations;

    alter table bw_eventann_exrules 
        add constraint bw_eann_erule_fk 
        foreign key (eventid) 
        references bw_event_annotations;

    alter table bw_eventann_rdates 
        add constraint bw_eann_rdate_fk 
        foreign key (eventid) 
        references bw_event_annotations;

    alter table bw_eventann_recipients 
        add constraint bw_eann_recip_fk 
        foreign key (eventid) 
        references bw_event_annotations;

    alter table bw_eventann_resources 
        add constraint bw_eann_res_fk 
        foreign key (bw_strid) 
        references bw_strings;

    alter table bw_eventann_resources 
        add constraint bw_eannres_eid_fk 
        foreign key (bw_eventid) 
        references bw_event_annotations;

    alter table bw_eventann_rrules 
        add constraint bw_eann_rrule_fk 
        foreign key (eventid) 
        references bw_event_annotations;

    alter table bw_eventann_rstatus 
        add constraint bw_eannrst_eid_fk 
        foreign key (eventid) 
        references bw_event_annotations;

    alter table bw_eventann_rstatus 
        add constraint bw_eann_rst_fk 
        foreign key (bw_rsdescid) 
        references bw_strings;

    alter table bw_eventann_summaries 
        add constraint bw_eann_sum_fk 
        foreign key (bw_strid) 
        references bw_strings;

    alter table bw_eventann_summaries 
        add constraint bw_eannsum_eid_fk 
        foreign key (bw_eventid) 
        references bw_event_annotations;

    alter table bw_eventann_xprops 
        add constraint bw_eventannxp_eid_fk 
        foreign key (bw_eventannid) 
        references bw_event_annotations;

    alter table bw_events 
        add constraint bw_event_loc_fk 
        foreign key (locationid) 
        references bw_locations;

    alter table bw_fbcomp 
        add constraint bw_eventfbc_eid_fk 
        foreign key (eventid) 
        references bw_events;

    alter table bw_filter_descriptions 
        add constraint bw_fktr_desc_fk 
        foreign key (bw_strid) 
        references bw_longstrings;

    alter table bw_filter_descriptions 
        add constraint bw_fltrdesc_eid_fk 
        foreign key (bw_eventid) 
        references bw_filters;

    alter table bw_filter_display_names 
        add constraint bw_fltrdname_fk 
        foreign key (bw_strid) 
        references bw_strings;

    alter table bw_filter_display_names 
        add constraint bw_fltrdname_eid_fk 
        foreign key (bw_eventid) 
        references bw_filters;

    alter table bw_group_Members 
        add constraint bw_grp_grp_fk 
        foreign key (groupid) 
        references bw_groups;

    alter table bw_locations 
        add constraint bw_loc_addr_fk 
        foreign key (bw_locaddrid) 
        references bw_strings;

    alter table bw_locations 
        add constraint bw_loc_sadd_fk 
        foreign key (bw_locsubaddrid) 
        references bw_strings;

    alter table bw_recurrences 
        add constraint bw_ri_mstr_fk 
        foreign key (masterid) 
        references bw_events;

    alter table bw_recurrences 
        add constraint bw_ri_ov_fk 
        foreign key (overrideid) 
        references bw_event_annotations;

    alter table bw_rstatus 
        add constraint bw_eventrst_eid_fk 
        foreign key (eventid) 
        references bw_events;

    alter table bw_rstatus 
        add constraint bw_event_rst_fk 
        foreign key (bw_rsdescid) 
        references bw_strings;

    alter table bw_system_properties 
        add constraint bw_sysprp_pid_fk 
        foreign key (bwid) 
        references bw_settings;

    alter table bw_user_properties 
        add constraint bw_prprp_pid_fk 
        foreign key (bwid) 
        references bw_preferences;

    alter table bw_user_views 
        add constraint bw_pr_view_fk 
        foreign key (elt) 
        references bw_views;

    alter table bw_user_views 
        add constraint bw_prview_pid_fk 
        foreign key (prefid) 
        references bw_preferences;

    alter table bw_view_collections 
        add constraint bw_cal_vid_fk 
        foreign key (viewid) 
        references bw_views;
